### ISSUE TITLE
&& getting escaped as HTML in Markdown

### ISSUE THREAD

**Issue by Serneum** [JohannesHoppe/markdown-shortcode#1]
GitHub will convert it, but the Markdown is 

```
override func sendEvent(event: NSEvent) {
    if (event.type == .SystemDefined && event.subtype.rawValue == 8) {
        let keyCode = ((event.data1 & 0xFFFF0000) >> 16)
        let keyFlags = (event.data1 & 0x0000FFFF)
        // Get the key state. 0xA is KeyDown, OxB is KeyUp
        let keyState = (((keyFlags & 0xFF00) >> 8)) == 0xA
        let keyRepeat = (keyFlags & 0x1)
        mediaKeyEvent(Int32(keyCode), state: keyState, keyRepeat: Bool(keyRepeat))
    }

    super.sendEvent(event)
}
```

Basically, everywhere & appears, it's getting replaced by `&#038;`. Oddly enough, if there are two next to each other, only the first one gets escaped.

![Screenshot](http://i.imgur.com/7RAnhkT.png)

**Comment by JohannesHoppe** [comment]
I can confirm. Will look on this in the evening...

**Comment by JohannesHoppe** [comment]
one line of code should fix it, see **markdown-shortcode.php**

```
// Reverts changes that were applied by the Visual editor
function undo_html_entities($content){
    $content = str_replace("&lt;", "<", $content);
    $content = str_replace("&gt;", ">", $content);
    $content = str_replace("&amp;", "&", $content); // NEW
    return $content;
}
```

Could you apply that line of code by hand?
And could you do me a favor and test for other characters, too? :-)

**Comment by JohannesHoppe** [comment]
see http://www.tinymce.com/wiki.php/Configuration%3aentity_encoding

pull requests are welcome! ;-)

**Comment by Serneum** [comment]
Tested it and got it to work. Of course, the fix was in the one file I didn't check for whatever reason :)
