### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by jaredcat** [JohannesHoppe/markdown-shortcode#3]
Conflicting with [DobsonDev Shortcodes](https://wordpress.org/plugins/dobsondev-shortcodes/) plugin.
`Fatal error: Cannot redeclare class Parsedown in /public_html/wp-content/plugins/markdown-shortcode/parsedown/Parsedown.php on line 17`

**Comment by JohannesHoppe** [comment]
That should be solvable. I will come up with a solution like this:

``` php
if( !class_exists( 'Parsedown' ) ) { }
```

**Comment by JohannesHoppe** [comment]
Ok, this should do the trick. I decided for namespaces.
1. Override the current version from wordpress.org with the latest version from github - Download: https://github.com/JohannesHoppe/markdown-shortcode/archive/master.zip
2. Please confirm that this change solves the conflict with the other plugin.
3. After confirmation I will publish an updated version on wordpress.org.

Thanks for your help! :smile:

**Comment by jaredcat** [comment]
Conflict resolved!

**Comment by JohannesHoppe** [comment]
I updated the plugin on wordpress.org. Don't forget to rate the plugin! ;-)
