### ISSUE TITLE
Fatal error: Class 'markdown_shortcode\DOMDocument'

### ISSUE THREAD

**Issue by jaredcat** [JohannesHoppe/markdown-shortcode#6]
`Fatal error: Class 'markdown_shortcode\DOMDocument' not found in /wp-content/plugins/markdown-shortcode/parsedown/ParsedownExtra.php on line 466`

Recreated by creating a post with the following in text mode:

```
[markdown]
<ol>
  <li></li>
</ol>
[/markdown]
```

**Comment by JohannesHoppe** [comment]
Thanks for reporting! :+1:
